version: '3'

services:
  my-app:
    build: .
    image: nodejsimage
    container_name: backend
    ports:
      - "4735:4735"
    volumes:
      - ./app:/usr/src/apphome/app
      - ./download:/usr/src/apphome/download
      - ./server.js:/usr/src/apphome/server.js
      
